### ISSUE TITLE
Group public instances showing as group+

### ISSUE THREAD

**Issue by ImLvna** [Nyabsi/VRCAA#66]
Title explains it
![image](https://github.com/user-attachments/assets/bca1f2ae-bb54-4712-8b18-248ed6dbdac8)

I would fix this myself but my ide doesnt like vrcaa

**Comment by Nyabsi** [comment]
I am pretty certain this is the correct behaviour? My code is identical to VRCX...

It's labeled as "Group+" because it's a instance that is also shown even if you're not in a Group, whereas Group instances are only visible to Group members. 

I'm not sure if this is actual proper classification by VRChat though.

**Comment by ImLvna** [comment]
group public instances are the same as public where anyone can join, the difference being the group has full moderation over it and can kick/ban from their instance

**Comment by Nyabsi** [comment]
Should be fixed by https://github.com/Nyabsi/VRCAA/commit/d248c7a7d972bf3f83e65e6bbfd1137df6dc4f9a
